# Generated by Django 4.0.1 on 2022-01-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profle_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create',
            new_name='created',
        ),
    ]
